# Generated by Django 4.2.4 on 2024-05-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Drama', 'Drama')], default='Unknown', max_length=100),
        ),
    ]
